- id: dbt-formatter
  name: dbt-formatter
  entry: dbt-formatter
  language: docker
  description: 'Formats DBT with `dbt-formatter`'
  types: [sql]
  files: ".*/(?:models|macros|snapshots|tests)/.*/.*.sql"
  require_serial: true
